--1
SELECT 
SUM(vl_preco_unitario*qt_estoque) "VALOR TOTAL EM ESTOQUE"
FROM T_SPV_PRODUTO;
--2
SELECT MAX(VL_TOTAL_NF) "MAIOR NOTA FISCAL"
FROM T_SPV_NOTA_FISCAL;
--3
SELECT MIN(VL_TOTAL_NF) "MENOR NOTA FISCAL"
FROM T_SPV_NOTA_FISCAL;
--4
SELECT AVG(VL_DESCONTO) "VALOR MÉDIO DE DESCONTO"
FROM T_SPV_NOTA_FISCAL;
--5
SELECT AVG(VL_TOTAL_NF)  "VALOR MÉDIO DAS VENDAS"
FROM T_SPV_NOTA_FISCAL;
--6
SELECT  NF.cd_cliente "COD.CLIENTE" ,
        cli.nm_cliente "CLIENTE" ,
        COUNT(nf.CD_CLIENTE) "QTDE. NOTA FISCAL POR CLIENTE" 
FROM T_SPV_NOTA_FISCAL NF inner join T_SPV_CLIENTE CLI
on (NF.CD_CLIENTE=CLI.CD_CLIENTE)
GROUP BY nf.CD_CLIENTE,cli.nm_cliente;

--7
SELECT  NF.cd_cliente "COD.CLIENTE" ,
         cli.nm_cliente "CLIENTE" ,
        COUNT(nf.CD_CLIENTE) "QTDE. NOTA FISCAL POR CLIENTE" 
FROM T_SPV_NOTA_FISCAL NF inner join T_SPV_CLIENTE CLI on (NF.CD_CLIENTE=CLI.CD_CLIENTE)
GROUP BY nf.CD_CLIENTE,cli.nm_cliente
Having COUNT(nf.CD_CLIENTE)>0;
--8
SELECT COUNT(CD_CLIENTE) "QTDE. NOTA FISCAL POR CLIENTE"
FROM T_SPV_NOTA_FISCAL 
WHERE dt_emissao Between TO_DATE('01/08/2014','DD/MM/YYYY') AND TO_DATE('31/08/2014','DD/MM/YYYY')  ;
--9
SELECT cli.nm_cliente,SUM(VL_TOTAL_NF) 
FROM T_SPV_NOTA_FISCAL NF inner join T_SPV_CLIENTE CLI on (NF.CD_CLIENTE=CLI.CD_CLIENTE)
GROUP BY cli.nm_cliente; 
--10
SELECT cli.nm_cliente,sum((nf.vl_total_nf * nf.vl_desconto) / 100)  "TOT. DESC.CONCEDIDO/CLIENTE"
FROM T_SPV_NOTA_FISCAL NF inner join T_SPV_CLIENTE CLI on (NF.CD_CLIENTE=CLI.CD_CLIENTE)
GROUP BY nf.cd_cliente,cli.nm_cliente;
--11
SELECT sum((nf.vl_total_nf * nf.vl_desconto) / 100)  "TOT. DESC.CONCEDIDO/CLIENTE"
FROM T_SPV_NOTA_FISCAL NF inner join T_SPV_CLIENTE CLI on (NF.CD_CLIENTE=CLI.CD_CLIENTE)
GROUP BY nf.cd_cliente
having sum((nf.vl_total_nf * nf.vl_desconto) / 100)>10;
--12
SELECT   ROW_NUMBER() OVER (ORDER BY  SUM(VL_TOTAL_NF)DESC) "RANK",
         (SELECT nm_cliente
          FROM T_SPV_CLIENTE cli
          WHERE cli.cd_cliente=nf.cd_cliente) "NOME",
       SUM(VL_TOTAL_NF)  "CLIENTE COM MAIOR COMPRA"
FROM T_SPV_NOTA_FISCAL NF 
GROUP BY nf.CD_CLIENTE;
--13
SELECT   ROW_NUMBER() OVER (ORDER BY  SUM(VL_TOTAL_NF)DESC) "RANK",
         (SELECT nm_cliente
          FROM T_SPV_CLIENTE cli
          WHERE cli.cd_cliente=nf.cd_cliente) "NOME",
       SUM(VL_TOTAL_NF)  "CLIENTE COM MAIOR COMPRA"
FROM T_SPV_NOTA_FISCAL NF 
WHERE ROWNUM =1
GROUP BY nf.CD_CLIENTE;
--14
