--1
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
D.NM_DEPENDENTE "DEPENDENTE",
D.DT_NASCIMENTO "DATA NASCIMENTO"
FROM T_SIP_FUNCIONARIO F ,
T_SIP_DEPENDENTE D
WHERE F.NR_MATRICULA=D.NR_MATRICULA
ORDER BY F.NM_FUNCIONARIO ASC,D.NM_DEPENDENTE ASC;

--2
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
D.NM_DEPENDENTE "DEPENDENTE",
D.DT_NASCIMENTO "DATA NASCIMENTO"
FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
ON( F.NR_MATRICULA=D.NR_MATRICULA)
ORDER BY F.NM_FUNCIONARIO ASC,D.NM_DEPENDENTE ASC;

--3
SELECT DEP.NM_DEPTO "DEPARTAMENTO",
F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
D.NM_DEPENDENTE "DEPENDENTE",
D.DT_NASCIMENTO "DATA NASCIMENTO DEPENDENTE"
FROM T_SIP_DEPTO DEP,T_SIP_FUNCIONARIO F,T_SIP_DEPENDENTE D
WHERE DEP.CD_DEPTO=F.CD_DEPTO
AND F.NR_MATRICULA=D.NR_MATRICULA
ORDER BY F.NR_MATRICULA ASC,D.NM_DEPENDENTE ASC;

--4
SELECT NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
DEP.NM_DEPTO "DEPARTAMENTO",
D.NM_DEPENDENTE "NOME DEPARTAMENTO",
D.DT_NASCIMENTO "DATA NASCIMENTO DEPENDENTE"
FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
USING(NR_MATRICULA)
INNER JOIN T_SIP_DEPTO DEP
USING (CD_DEPTO)
ORDER BY NR_MATRICULA ASC,D.NM_DEPENDENTE ASC;

--5

SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICÍO",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "DATA ENTRADA",
I.DT_SAIDA "DATA SAIDA"
FROM T_SIP_FUNCIONARIO F, T_SIP_IMPLANTACAO I,T_SIP_PROJETO P
WHERE F.NR_MATRICULA=I.NR_MATRICULA AND 
P.CD_PROJETO=I.CD_PROJETO
ORDER BY P.NM_PROJETO ASC,
F.NM_FUNCIONARIO ASC;

--6
SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICÍO",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "DATA ENTRADA",
I.DT_SAIDA "DATA SAIDA"
FROM T_SIP_FUNCIONARIO F, T_SIP_IMPLANTACAO I,T_SIP_PROJETO P
WHERE F.NR_MATRICULA=I.NR_MATRICULA AND 
P.CD_PROJETO=I.CD_PROJETO AND
P.DT_TERMINO IS NULL
ORDER BY P.NM_PROJETO ASC,F.NM_FUNCIONARIO ASC;


--7
SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICÍO",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "DATA ENTRADA",
I.DT_SAIDA "DATA SAIDA"
FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_IMPLANTACAO I
ON(F.NR_MATRICULA=I.NR_MATRICULA)
INNER JOIN T_SIP_PROJETO P
ON(P.CD_PROJETO=I.CD_PROJETO)
WHERE P.DT_TERMINO IS NULL
ORDER BY P.NM_PROJETO ASC,F.NM_FUNCIONARIO ASC;