CREATE SEQUENCE PAO
INCREMENT BY 1
START WITH 1
MAXVALUE 999

NOCACHE

NOCYCLE;

create table T_EX_CARRO
(ID_CARRO NUMERIC,
NM_CONDUTOR VARCHAR2 (50),
NR_CARRO NUMERIC(1),
DS_PLACA VARCHAR(50)
);

ALTER TABLE T_EX_CARRO
ADD CONSTRAINT PK_EX_CARRO
PRIMARY KEY (ID_CARRO);