--1
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
D.NM_DEPENDENTE "DEPENDENTE",
D.DT_NASCIMENTO "DATA NASCIMENTO DEPENDENTE"
FROM T_SIP_FUNCIONARIO F LEFT OUTER JOIN T_SIP_DEPENDENTE D
ON(F.NR_MATRICULA=D.NR_MATRICULA)
WHERE D.NR_MATRICULA IS NULL
ORDER BY F.NM_FUNCIONARIO ASC;


--2
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
D.NM_DEPENDENTE "DEPENDENTE",
D.DT_NASCIMENTO "DATA NASCIMENTO DEPENDENTE"
FROM T_SIP_FUNCIONARIO F , T_SIP_DEPENDENTE D
WHERE F.NR_MATRICULA=D.NR_MATRICULA(+) AND
 D.NR_MATRICULA IS NULL
ORDER BY F.NM_FUNCIONARIO ASC; 

--3
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "ENTRADA EM:"
FROM T_SIP_FUNCIONARIO F RIGHT OUTER JOIN T_SIP_IMPLANTACAO I
ON(F.NR_MATRICULA=I.NR_MATRICULA)
ORDER BY F.NM_FUNCIONARIO ASC,I.CD_IMPLANTACAO ASC;

--4
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "ENTRADA EM:"
FROM T_SIP_FUNCIONARIO F ,T_SIP_IMPLANTACAO I
WHERE F.NR_MATRICULA(+)=I.NR_MATRICULA
ORDER BY F.NM_FUNCIONARIO ASC,I.CD_IMPLANTACAO ASC;

--5
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "ENTRADA EM:"
FROM T_SIP_FUNCIONARIO F LEFT OUTER JOIN T_SIP_IMPLANTACAO I
ON(F.NR_MATRICULA=I.NR_MATRICULA)
ORDER BY F.NM_FUNCIONARIO ASC,I.CD_IMPLANTACAO ASC;

--6
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "ENTRADA EM:"
FROM T_SIP_FUNCIONARIO F,T_SIP_IMPLANTACAO I
WHERE F.NR_MATRICULA=I.NR_MATRICULA(+)
ORDER BY F.NM_FUNCIONARIO ASC,I.CD_IMPLANTACAO ASC;


--7
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "ENTRADA EM:"
FROM T_SIP_FUNCIONARIO F LEFT OUTER JOIN T_SIP_IMPLANTACAO I
ON (F.NR_MATRICULA=I.NR_MATRICULA)
WHERE I.NR_MATRICULA IS NULL
ORDER BY F.NM_FUNCIONARIO ASC,I.CD_IMPLANTACAO ASC;
--8
SELECT F.NR_MATRICULA "MATRICULA",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
I.DT_ENTRADA "ENTRADA EM:"
FROM T_SIP_FUNCIONARIO F,T_SIP_IMPLANTACAO I
WHERE F.NR_MATRICULA=I.NR_MATRICULA(+) AND 
I.NR_MATRICULA IS NULL
ORDER BY F.NM_FUNCIONARIO ASC,I.CD_IMPLANTACAO ASC;

--9
SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICIADO EM:",
I.CD_IMPLANTACAO "CD.IMPLANTACAO"
FROM T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
ON(P.CD_PROJETO=I.CD_PROJETO)
WHERE I.CD_PROJETO IS NULL
ORDER BY P.NM_PROJETO ASC;


--10
SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICIADO EM:",
I.CD_IMPLANTACAO "CD.IMPLANTACAO"
FROM T_SIP_PROJETO P,T_SIP_IMPLANTACAO I
WHERE P.CD_PROJETO=I.CD_PROJETO(+) AND
 I.CD_PROJETO IS NULL
ORDER BY P.NM_PROJETO ASC;

--11
SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICIADO EM:",
P.DT_TERMINO "TERMINO EM:",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.DT_ENTRADA "ENTRADA",
I.DT_SAIDA "SAIDA"
FROM T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
ON(P.CD_PROJETO=I.CD_PROJETO)
INNER JOIN  T_SIP_FUNCIONARIO F
ON(F.NR_MATRICULA=I.NR_MATRICULA)
WHERE I.CD_PROJETO IS NOT NULL
ORDER BY P.NM_PROJETO ASC,I.DT_ENTRADA ASC,F.NM_FUNCIONARIO ASC;


--12
SELECT P.CD_PROJETO "CD.PROJETO",
P.NM_PROJETO "PROJETO",
P.DT_INICIO "INICIADO EM:",
P.DT_TERMINO "TERMINO EM:",
I.CD_IMPLANTACAO "CD.IMPLANTACAO",
F.NM_FUNCIONARIO "FUNCIONARIO",
I.DT_ENTRADA "ENTRADA",
I.DT_SAIDA "SAIDA"
FROM T_SIP_PROJETO P ,T_SIP_IMPLANTACAO I,T_SIP_FUNCIONARIO F
WHERE P.CD_PROJETO=I.CD_PROJETO(+) AND
F.NR_MATRICULA=I.NR_MATRICULA
AND I.CD_PROJETO IS NOT NULL
ORDER BY P.NM_PROJETO ASC,I.DT_ENTRADA ASC,F.NM_FUNCIONARIO ASC;





