--1
SELECT P.CD_PRODUTO "CODIGO PRODUTO",
UN.DS_SIGLA "SIGLA",
UN.DS_UNIDADE_MEDIDA "DESC UNID MEDIDA",
P.DS_PRODUTO "DESCRICAO PRODUTO",
P.DS_COMPLETA_PRODUTO "DESC COMPLETA",
P.QT_ESTOQUE "ESTOQUE",
P.VL_PRECO_UNITARIO "PREÇO"
FROM T_SPV_PRODUTO P  INNER JOIN T_SPV_UNIDADE_MEDIDA UN 
USING(CD_UNIDADE_MEDIDA)
ORDER BY P.DS_PRODUTO ASC;

--2
SELECT P.CD_PRODUTO "CODIGO PRODUTO",
UN.DS_SIGLA "SIGLA",
UN.DS_UNIDADE_MEDIDA "DESC UNID MEDIDA",
P.DS_PRODUTO "DESCRICAO PRODUTO",
P.DS_COMPLETA_PRODUTO "DESC COMPLETA",
P.QT_ESTOQUE "ESTOQUE",
P.VL_PRECO_UNITARIO "PREÇO"
FROM T_SPV_PRODUTO P ,T_SPV_UNIDADE_MEDIDA UN 
WHERE P.CD_UNIDADE_MEDIDA = UN.CD_UNIDADE_MEDIDA
ORDER BY P.DS_PRODUTO ASC;


--3
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CF.NR_CFOP "CFOP",
CF.DS_NATUREZA_OPERACAO "NATUREZA OPERACAO",
NF.DT_EMISSAO "DT.EMISSAO",
NF.VL_TOTAL_NF "VL.TOTAL NF",
NF.VL_DESCONTO "% DESCONTO",
(NF.VL_TOTAL_NF *(NF.VL_DESCONTO/100)) "VL DESCONTO"
FROM T_SPV_NOTA_FISCAL NF INNER JOIN T_SPV_CLASSIFICACAO_FISCAL CF
ON(NF.CD_CLASSIFICACAO_FISCAL=CF.CD_CLASSIFICACAO_FISCAL)
WHERE NF.VL_DESCONTO IS NOT NULL
ORDER BY NF.NR_NOTA_FISCAL ASC;

--4
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CF.NR_CFOP "CFOP",
CF.DS_NATUREZA_OPERACAO "NATUREZA OPERACAO",
NF.DT_EMISSAO "DT.EMISSAO",
NF.VL_TOTAL_NF "VL.TOTAL NF",
NF.VL_DESCONTO "% DESCONTO",
(NF.VL_TOTAL_NF *(NF.VL_DESCONTO/100)) "VL DESCONTO"
FROM T_SPV_NOTA_FISCAL NF ,T_SPV_CLASSIFICACAO_FISCAL CF
WHERE NF.CD_CLASSIFICACAO_FISCAL=CF.CD_CLASSIFICACAO_FISCAL
AND NF.VL_DESCONTO IS NOT NULL
ORDER BY NF.NR_NOTA_FISCAL ASC;

--5
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CF.NR_CFOP "CFOP",
CF.DS_NATUREZA_OPERACAO "NATUREZA OPERACAO",
NF.DT_EMISSAO "DATA EMISSAO",
NF.DS_TIPO "TIPO NF",
NF.VL_TOTAL_NF "VL.TOTAL NF",
NF.VL_DESCONTO "% DESCONTO"
FROM T_SPV_NOTA_FISCAL NF INNER JOIN T_SPV_CLASSIFICACAO_FISCAL CF
ON(NF.CD_CLASSIFICACAO_FISCAL=CF.CD_CLASSIFICACAO_FISCAL)
WHERE TO_CHAR(NF.DT_EMISSAO,'YYYY') IN('2013','2014') AND NF.VL_DESCONTO IS NOT NULL
ORDER BY NF.NR_NOTA_FISCAL;

--6
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CF.NR_CFOP "CFOP",
CF.DS_NATUREZA_OPERACAO "NATUREZA OPERACAO",
NF.DT_EMISSAO "DATA EMISSAO",
NF.DS_TIPO "TIPO NF",
NF.VL_TOTAL_NF "VL.TOTAL NF",
NF.VL_DESCONTO "% DESCONTO"
FROM T_SPV_NOTA_FISCAL NF , T_SPV_CLASSIFICACAO_FISCAL CF
WHERE NF.CD_CLASSIFICACAO_FISCAL=CF.CD_CLASSIFICACAO_FISCAL
AND TO_CHAR(NF.DT_EMISSAO,'YYYY') IN('2013','2014') AND NF.VL_DESCONTO IS NOT NULL;


--7
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
CF.NR_CFOP "CFOP" ,
CF.DS_NATUREZA_OPERACAO "NATUREZA OPERACAO",
NF.DT_EMISSAO "DATA EMISSAO",
NF.VL_TOTAL_NF "VL.TOTAL NF",
NF.VL_DESCONTO "% DESCONTO"
FROM T_SPV_CLASSIFICACAO_FISCAL CF INNER JOIN T_SPV_NOTA_FISCAL NF
ON(CF.CD_CLASSIFICACAO_FISCAL=NF.CD_CLASSIFICACAO_FISCAL)
INNER JOIN T_SPV_CLIENTE CLI
ON(CLI.CD_CLIENTE=NF.CD_CLIENTE)
ORDER BY CLI.NM_CLIENTE ASC,NF.NR_NOTA_FISCAL ASC;


--8
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
CF.NR_CFOP "CFOP" ,
CF.DS_NATUREZA_OPERACAO "NATUREZA OPERACAO",
NF.DT_EMISSAO "DATA EMISSAO",
NF.VL_TOTAL_NF "VL.TOTAL NF",
NF.VL_DESCONTO "% DESCONTO"
FROM T_SPV_CLASSIFICACAO_FISCAL CF,T_SPV_NOTA_FISCAL NF,T_SPV_CLIENTE CLI
WHERE CF.CD_CLASSIFICACAO_FISCAL=NF.CD_CLASSIFICACAO_FISCAL AND
CLI.CD_CLIENTE=NF.CD_CLIENTE
ORDER BY CLI.NM_CLIENTE ASC,NF.NR_NOTA_FISCAL ASC;

--9
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
INF.CD_ITEM "ITEM",
'SIGLA:' || UN.DS_SIGLA ||
' DESCRIÇÃO SIGLA:' || UN.DS_UNIDADE_MEDIDA "UN.MEDIDA",
P.DS_PRODUTO "PRODUTO",
(SELECT P.VL_PRECO_UNITARIO FROM T_SPV_PRODUTO P WHERE P.CD_PRODUTO=INF.CD_PRODUTO )"PRECO UNIT",
INF.QT_VENDIDA "QTDE. VENDIDA",
P.VL_PRECO_UNITARIO "PRECO.UNIT",
(INF.QT_VENDIDA * INF.VL_PRECO_UNITARIO) "VL.TOTAL ITEM"
FROM T_SPV_NOTA_FISCAL NF INNER JOIN T_SPV_CLIENTE CLI
ON(NF.CD_CLIENTE=CLI.CD_CLIENTE)
INNER JOIN T_SPV_ITEM_NOTA_FISCAL INF
ON(INF.NR_NOTA_FISCAL=NF.NR_NOTA_FISCAL)
INNER JOIN T_SPV_PRODUTO P
ON(INF.CD_PRODUTO=P.CD_PRODUTO)
INNER JOIN T_SPV_UNIDADE_MEDIDA UN
ON(UN.CD_UNIDADE_MEDIDA=P.CD_UNIDADE_MEDIDA)

ORDER BY NF.NR_NOTA_FISCAL ASC,CLI.NM_CLIENTE ASC;

--10
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
INF.NR_NOTA_FISCAL "ITEM",
'SIGLA: ' || UN.DS_SIGLA ||
'DESCRIÇÃO SIGLA' || UN.DS_UNIDADE_MEDIDA "UN.MEDIDA",
P.DS_PRODUTO "PRODUTO",
(SELECT P.VL_PRECO_UNITARIO FROM T_SPV_PRODUTO P WHERE P.CD_PRODUTO=INF.CD_PRODUTO )"PRECO UNITARIO",
INF.QT_VENDIDA "QTDE. VENDIDA",
P.VL_PRECO_UNITARIO "PRECO.UNIT",
(INF.QT_VENDIDA * INF.VL_PRECO_UNITARIO) "VL.TOTAL ITEM"
FROM T_SPV_NOTA_FISCAL NF,T_SPV_CLIENTE CLI,T_SPV_ITEM_NOTA_FISCAL INF,T_SPV_PRODUTO P,T_SPV_UNIDADE_MEDIDA UN
WHERE NF.CD_CLIENTE=CLI.CD_CLIENTE
AND(INF.NR_NOTA_FISCAL=NF.NR_NOTA_FISCAL)
AND(INF.CD_PRODUTO=P.CD_PRODUTO)
AND(UN.CD_UNIDADE_MEDIDA=P.CD_UNIDADE_MEDIDA)
ORDER BY NF.NR_NOTA_FISCAL ASC,INF.CD_ITEM ASC;

--11
SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
INF.NR_NOTA_FISCAL "ITEM",
'SIGLA:' || UN.DS_SIGLA ||
' DESCRIÇÃO SIGLA:' || UN.DS_UNIDADE_MEDIDA "UN.MEDIDA",
P.DS_PRODUTO "PRODUTO",
P.VL_PRECO_UNITARIO "PRECO_UNITARIO",
INF.QT_VENDIDA "QTDE. VENDIDA",
P.VL_PRECO_UNITARIO "PRECO.UNIT",
(INF.QT_VENDIDA * INF.VL_PRECO_UNITARIO) "VL.TOTAL ITEM"
FROM T_SPV_NOTA_FISCAL NF INNER JOIN T_SPV_CLIENTE CLI
ON(NF.CD_CLIENTE=CLI.CD_CLIENTE)
INNER JOIN T_SPV_ITEM_NOTA_FISCAL INF
ON(INF.NR_NOTA_FISCAL=NF.NR_NOTA_FISCAL)
INNER JOIN T_SPV_PRODUTO P
ON(INF.CD_PRODUTO=P.CD_PRODUTO)
INNER JOIN T_SPV_UNIDADE_MEDIDA UN
ON(UN.CD_UNIDADE_MEDIDA=P.CD_UNIDADE_MEDIDA)

ORDER BY NF.NR_NOTA_FISCAL ASC,INF.CD_ITEM ASC;


--12
SELECT P.CD_PRODUTO "CD. PRODUTO",
'SIGLA:' || UN.DS_SIGLA ||
' DESCRIÇÃO SIGLA:' || UN.DS_UNIDADE_MEDIDA "UN.MEDIDA",
P.DS_PRODUTO "PRODUTO",
P.QT_ESTOQUE "QTDE ESTOQUE",
P.VL_PRECO_UNITARIO "PRECO UNITARIO",
INF.CD_ITEM "NR.ITEM"
FROM T_SPV_PRODUTO P LEFT OUTER JOIN T_SPV_ITEM_NOTA_FISCAL INF
ON(P.CD_PRODUTO=INF.CD_PRODUTO)
INNER JOIN T_SPV_UNIDADE_MEDIDA UN
ON(UN.CD_UNIDADE_MEDIDA=P.CD_UNIDADE_MEDIDA)
WHERE INF.CD_ITEM IS NULL
ORDER BY P.DS_PRODUTO;

--13
SELECT P.CD_PRODUTO "CD. PRODUTO",
'SIGLA:' || UN.DS_SIGLA ||
' DESCRIÇÃO SIGLA:' || UN.DS_UNIDADE_MEDIDA "UN.MEDIDA",
P.DS_PRODUTO "PRODUTO",
P.QT_ESTOQUE "QTDE ESTOQUE",
P.VL_PRECO_UNITARIO "PRECO UNITARIO",
INF.CD_ITEM "NR.ITEM"
FROM T_SPV_PRODUTO P ,T_SPV_ITEM_NOTA_FISCAL INF ,T_SPV_UNIDADE_MEDIDA UN
WHERE P.CD_PRODUTO=INF.CD_PRODUTO(+)
AND UN.CD_UNIDADE_MEDIDA=P.CD_UNIDADE_MEDIDA
AND INF.CD_ITEM IS NULL
ORDER BY P.DS_PRODUTO;

--14
SELECT ROWNUM "RANK",
"NR.NF",
"CLIENTE",
"VL.TOTAL NF"
FROM(SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
NF.VL_TOTAL_NF "VL.TOTAL NF"
FROM T_SPV_CLIENTE CLI INNER JOIN T_SPV_NOTA_FISCAL NF
ON(NF.CD_CLIENTE=CLI.CD_CLIENTE)
ORDER BY NF.VL_TOTAL_NF DESC)
WHERE ROWNUM <4;

--15

SELECT ROWNUM "RANK",
"NR.NF",
"CLIENTE",
"VL.TOTAL NF"
FROM(SELECT NF.NR_NOTA_FISCAL "NR.NF",
CLI.NM_CLIENTE "CLIENTE",
NF.VL_TOTAL_NF "VL.TOTAL NF"
FROM T_SPV_CLIENTE CLI,T_SPV_NOTA_FISCAL NF
WHERE NF.CD_CLIENTE=CLI.CD_CLIENTE
ORDER BY NF.VL_TOTAL_NF DESC)
WHERE ROWNUM <4;

--16
SELECT CD.CD_CODIGO_CD "COD.CD",
CD.DS_CD "TÍTULO",
CD.DT_LANCAMENTO "DT.LANÇAMENTO",
CD.VL_PRECO_VENDA "PREÇO VENDA",
CAT.DS_CATEGORIA "CATEGORIA",
'ENTRE '||CAT.VL_INICIAL ||
'E '||CAT.VL_FINAL "FAIXA DE VALOR"
FROM T_AULA27_CD CD ,T_AULA27_CATEGORIA CAT
WHERE CD.VL_PRECO_VENDA BETWEEN CAT.VL_INICIAL AND CAT.VL_FINAL;





